version: "3.9"
services:
  mongo:
    image: mongo:latest
    #    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express:latest
    #    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      #      ME_CONFIG_MONGODB_ENABLE_ADMIN: false
      #      ME_CONFIG_MONGODB_AUTH_DATABASE: ${MONGO_DATABASE}
      #      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_ROOT_USER}
      #      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - mongo
    ports:
      - "8081:8081"
volumes:
  mongo-data:
